Part 3 - WATER SYSTEMS

Scrape the search results page from https://dww.des.sc.gov/DWW/ Links to an external site.which includes submitting the form - and include the link. Save as a CSV. Since it's more than just the text from the table, this requires actually using BeautifulSoup :(

Tips:

We talked about form submission being for Playwright, but in this situation submitting the form gets you a nice URL full of parameters! Use that.
In class we always did something like item.find('h2') or the like because there was only ever one h2 we wanted. In this case there are multiple <td> tags that you want the text from! You'll need to use .find_all and treat them like normal lists ("give me the text from the first one," + "give me the text from the second one" etc etc)
It's okay to have columns you don't want or need! You can always remove them later
You'll need to grab the right <table> from the page before anything else

#### Note on try-except 

1 Instead of just if/else - tests for condition - true/false
2 In scraping, there are many ways a line can fail (missing tag, missing attribute, etc.) and you don't have to predict which — you just catch them all.
3 when return fails, just put a None in the cell and scrape the next row


#### Build 2 csvs
Include the URL in this version of the CSV. then in round 2 scraping, then use this csv's URL to build a csv for each individual cases. 


#### Ways to reach inside a css tag 

1 An HTML attribute (= written inside the tag,href, src, class) 
[] = pull a key from a dictionary

link['href'], img['src'] 

vs

2 BeautifulSoup feature/method	 
link.text,strip()              .find('a')['href']

3 
.text = "give me the words, throw away the HTML tags."

.strip() = "clean the empty space off the front and back.

## Round 1 - Failed attempt 1
<table> tag is not sufficient

Question 1 - how to scrape table with a table - what is a good structure?

In [24]:
import pandas as pd

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
}

tables = pd.read_html(
    'https://dww.des.sc.gov/DWW/JSP/SearchDispatch?number=&name=&county=All&WaterSystemType=All&SourceWaterType=All&PointOfContactType=None&SampleType=ColiformSample&begin_date=6%2F19%2F2024&end_date=6%2F19%2F2026&action=Search+For+Water+Systems',
    storage_options=headers
)

In [25]:
tables

[                                                   0  \
 0                                                NaN
 1  Return Links  Water  System Search County Map ...
 2                                                NaN

                                                    1
 0                              Drinking Water Branch
 1  Water Systems  Water  System No.  Water  Syste...
 2           Total Number of Records Displayed = 1392  ,
                    0                   1     2       3  \
 0  Water  System No.  Water  System Name  Type  Status

                           4                           5
 0  Principal  County Served  Primary  Source Water Type  ]

In [27]:
len(tables)

2

In [43]:
df = tables[1]

In [44]:
df

,0,1,2,3,4,5
0,Water System No.,Water System Name,Type,Status,Principal County Served,Primary Source Water Type

#### Other approaches to try - Try playwrite for alternative setup for form request

In [ ]:
%pip install playwright
%pip install playwright

Requirement already satisfied: playwright in /Users/mangojackson/.venvs/lede/lib/python3.13/site-packages (1.60.0)
Requirement already satisfied: pyee<14,>=13 in /Users/mangojackson/.venvs/lede/lib/python3.13/site-packages (from playwright) (13.0.1)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /Users/mangojackson/.venvs/lede/lib/python3.13/site-packages (from playwright) (3.5.2)
Requirement already satisfied: typing-extensions in /Users/mangojackson/.venvs/lede/lib/python3.13/site-packages (from pyee<14,>=13->playwright) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
%pip install playwright

Requirement already satisfied: playwright in /Users/mangojackson/.venvs/lede/lib/python3.13/site-packages (1.60.0)
Requirement already satisfied: pyee<14,>=13 in /Users/mangojackson/.venvs/lede/lib/python3.13/site-packages (from playwright) (13.0.1)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /Users/mangojackson/.venvs/lede/lib/python3.13/site-packages (from playwright) (3.5.2)
Requirement already satisfied: typing-extensions in /Users/mangojackson/.venvs/lede/lib/python3.13/site-packages (from pyee<14,>=13->playwright) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import sys
!{sys.executable} -m playwright install chromium

In [14]:
# Imports
from playwright.async_api import async_playwright

playwright = await async_playwright().start()
browser = await playwright.chromium.launch(headless = False)
page = await browser.new_page()

await page.goto("https://dww.des.sc.gov/DWW/")

## Solution using lxml

In [68]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
import pandas as pd

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
}

tables = pd.read_html(
    'https://dww.des.sc.gov/DWW/JSP/SearchDispatch?number=&name=&county=All&WaterSystemType=All&SourceWaterType=All&PointOfContactType=None&SampleType=ColiformSample&begin_date=6%2F19%2F2024&end_date=6%2F19%2F2026&action=Search+For+Water+Systems',
    storage_options=headers
)

Tips: instead of pulling a table, understand the table structure here:

In [ ]:
# <table> - Query this is not useful here
#     <tr> -- naming for headers
#     <tr> - the first case 
#         <td> case number *** use index to get to each order - [0].text.strip()
#         <td> name

In [ ]:
response = requests.get('https://dww.des.sc.gov/DWW/JSP/SearchDispatch?number=&name=&county=All&WaterSystemType=All&SourceWaterType=All&PointOfContactType=None&SampleType=ColiformSample&begin_date=6%2F19%2F2024&end_date=6%2F19%2F2026&action=Search+For+Water+Systems')
doc = BeautifulSoup(response.text, 'lxml')   # was 'html.parser'
print(response.status_code)   # 200 means OK

In [70]:
table = doc.find('table', attrs={'id': 'AutoNumber7'})

rows = []
# skip the first <tr> because it's the header, not data
for tr in table.find_all('tr')[1:]:
    cells = tr.find_all('td')      # <-- "these" are the cells

    row = {}
    row['water_system_no']   = cells[0].text.strip()
    row['water_system_name'] = cells[1].text.strip()
    row['type']              = cells[2].text.strip()
    row['status']            = cells[3].text.strip()
    row['county']            = cells[4].text.strip()
    row['source_type']       = cells[5].text.strip()

    link = cells[0].find('a')  #already at the <a> link level
    #no need to wrtie as find('a')['href']

    try:
        row['link'] = link['href'] 
    except:
        row['link'] = None


    # link = cells[0].find('a')
    # row['link'] = link['href'] if link else None
    
    rows.append(row)

len(rows)

0

In [64]:
rows

[{'water_system_no': 'SC7777',
  'water_system_name': '123 WATER',
  'type': '',
  'status': 'A',
  'county': '',
  'source_type': '',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=7343&tinwsys_st_code=SC&wsnumber=SC7777      '},
 {'water_system_no': 'SC0874019',
  'water_system_name': '1250 OLD GILLIARD, LLC (SC0874019',
  'type': 'NC',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=7233&tinwsys_st_code=SC&wsnumber=SC0874019   '},
 {'water_system_no': 'SC2174000',
  'water_system_name': '341 EXPRESS (SC2174000)',
  'type': 'NC',
  'status': 'A',
  'county': 'FLORENCE',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=6979&tinwsys_st_code=SC&wsnumber=SC2174000   '},
 {'water_system_no': 'SC4570950',
  'water_system_name': '4 WAY STOP (SC4570950)',
  'type': 'NC',
  'status': 'A',
  'county': 'WILLIAMSBURG',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=6458&tinwsys_st_code=SC&wsnumber=SC4570950   '},
 {'water_system_no': 'SC4060012',
  'water_system_name': '611 HARMON LLC (SC4060012)',
  'type': 'C',
  'status': 'A',
  'county': 'RICHLAND',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=4254&tinwsys_st_code=SC&wsnumber=SC4060012   '},
 {'water_system_no': 'SC3870921',
  'water_system_name': '76 GAS STATION (SC3870921)',
  'type': 'NC',
  'status': 'A',
  'county': 'ORANGEBURG',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=4124&tinwsys_st_code=SC&wsnumber=SC3870921   '},
 {'water_system_no': 'SC4074011',
  'water_system_name': '7730 BLUFF ROAD CONVENIENCE (SC4074011)',
  'type': 'NC',
  'status': 'A',
  'county': 'RICHLAND',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=7317&tinwsys_st_code=SC&wsnumber=SC4074011   '},
 {'water_system_no': 'SC0110001',
  'water_system_name': 'ABBEVILLE CITY OF (SC0110001)',
  'type': 'C',
  'status': 'A',
  'county': 'ABBEVILLE',
  'source_type': 'SW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=1&tinwsys_st_code=SC&wsnumber=SC0110001   '},
 {'water_system_no': 'SC013000',
  'water_system_name': 'ABC',
  'type': '',
  'status': 'A',
  'county': '',
  'source_type': '',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=7337&tinwsys_st_code=SC&wsnumber=SC013000    '},
 {'water_system_no': 'SC075555',
  'water_system_name': 'ABC',
  'type': '',
  'status': 'A',
  'county': '',
  'source_type': '',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=7275&tinwsys_st_code=SC&wsnumber=SC075555    '},
 {'water_system_no': 'SC1070148',
  'water_system_name': 'ADAMS RUN CIVIC CENTER (SC1070148)',
  'type': 'NTNC',
  'status': 'A',
  'county': 'CHARLESTON',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=1169&tinwsys_st_code=SC&wsnumber=SC1070148   '},
 {'water_system_no': 'SC4660115',
  'water_system_name': 'ADNAH HILLS MHP (SC4660115)',
  'type': 'C',
  'status': 'A',
  'county': 'YORK',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=5079&tinwsys_st_code=SC&wsnumber=SC4660115   '},
 {'water_system_no': 'SC0670924',
  'water_system_name': 'ADVENTURE FARMS (SC0670924)',
  'type': 'NC',
  'status': 'A',
  'county': 'BARNWELL',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=7339&tinwsys_st_code=SC&wsnumber=SC0670924   '},
 {'water_system_no': 'SC0210001',
  'water_system_name': 'AIKEN CITY OF (SC0210001)',
  'type': 'C',
  'status': 'A',
  'county': 'AIKEN',
  'source_type': 'SW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=55&tinwsys_st_code=SC&wsnumber=SC0210001   '},
 {'water_system_no': 'SC0250009',
  'water_system_name': 'AIKEN-VALE SVC C CITY OF (SC0250009)',
  'type': 'C',
  'status': 'A',
  'county': 'AIKEN',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=113&tinwsys_st_code=SC&wsnumber=SC0250009   '},
 {'water_system_no': 'SC4672003',
  'water_system_name': "AK'S MART (SC4672003)",
  'type': 'NC',
  'status': 'A',
  'county': 'YORK',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=5237&tinwsys_st_code=SC&wsnumber=SC4672003   '},
 {'water_system_no': 'SC0320002',
  'water_system_name': 'ALLENDALE INDUSTRIAL PARK (SC0320002)',
  'type': 'C',
  'status': 'A',
  'county': 'ALLENDALE',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=200&tinwsys_st_code=SC&wsnumber=SC0320002   '},
 {'water_system_no': 'SC0310001',
  'water_system_name': 'ALLENDALE TOWN OF (SC0310001)',
  'type': 'C',
  'status': 'A',
  'county': 'ALLENDALE',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=196&tinwsys_st_code=SC&wsnumber=SC0310001   '},
 {'water_system_no': 'SC1320004',
  'water_system_name': 'ALLIGATOR RURAL WATER (SC1320004)',
  'type': 'C',
  'status': 'A',
  'county': 'CHESTERFIELD',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=1436&tinwsys_st_code=SC&wsnumber=SC1320004   '},
 {'water_system_no': 'SC4070940',
  'water_system_name': 'AM PM QUICK STOP (SC4070940)',
  'type': 'NC',
  'status': 'A',
  'county': 'RICHLAND',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=4407&tinwsys_st_code=SC&wsnumber=SC4070940   '},
 {'water_system_no': 'SC0770050',
  'water_system_name': 'AMI KIDS-BEAUFORT (0770050)',
  'type': 'NC',
  'status': 'A',
  'county': 'BEAUFORT',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=595&tinwsys_st_code=SC&wsnumber=SC0770050   '},
 {'water_system_no': 'SC2270906',
  'water_system_name': 'AMI KIDS-GEORGETOWN (2270906)',
  'type': 'NTNC',
  'status': 'A',
  'county': 'GEORGETOWN',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=2342&tinwsys_st_code=SC&wsnumber=SC2270906   '},
 {'water_system_no': 'SC3250077',
  'water_system_name': 'AMICKS FERRY WTR SYSTEM (SC3250077)',
  'type': 'C',
  'status': 'A',
  'county': 'LEXINGTON',
  'source_type': 'SWP',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=3446&tinwsys_st_code=SC&wsnumber=SC3250077   '},
 {'water_system_no': 'SC3830002',
  'water_system_name': 'AMRIZE (SC3830002)',
  'type': 'NTNC',
  'status': 'A',
  'county': 'ORANGEBURG',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=4019&tinwsys_st_code=SC&wsnumber=SC3830002   '},
 {'water_system_no': 'SC0420011',
  'water_system_name': 'ANDERSON REGIONAL JOINT WS (SC0420011)',
  'type': 'C',
  'status': 'A',
  'county': 'ANDERSON',
  'source_type': 'SW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=234&tinwsys_st_code=SC&wsnumber=SC0420011   '},
 {'water_system_no': 'SC0570100',
  'water_system_name': 'ANDREW JACKSON ACADEMY (0570100)',
  'type': 'NTNC',
  'status': 'A',
  'county': 'BAMBERG',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=396&tinwsys_st_code=SC&wsnumber=SC0570100   '},
 {'water_system_no': 'SC2210003',
  'water_system_name': 'ANDREWS TOWN OF (SC2210003)',
  'type': 'C',
  'status': 'A',
  'county': 'GEORGETOWN',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=2265&tinwsys_st_code=SC&wsnumber=SC2210003   '},
 {'water_system_no': 'SC0870809',
  'water_system_name': 'ANGELS CAMPGROUND I (SC0870809)',
  'type': 'NC',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=904&tinwsys_st_code=SC&wsnumber=SC0870809   '},
 {'water_system_no': 'SC0870810',
  'water_system_name': 'ANGELS CAMPGROUND II (0870810)',
  'type': 'NC',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=905&tinwsys_st_code=SC&wsnumber=SC0870810   '},
 {'water_system_no': 'SC0870215',
  'water_system_name': 'ANGELS LANDING RESTAURANT (SC0870215)',
  'type': 'NC',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=813&tinwsys_st_code=SC&wsnumber=SC0870215   '},
 {'water_system_no': 'SC0870805',
  'water_system_name': 'ANGELS TRAILER PARK (SC0870805)',
  'type': 'NC',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=900&tinwsys_st_code=SC&wsnumber=SC0870805   '},
 {'water_system_no': 'SC0330001',
  'water_system_name': 'ARCHROMA US INC (0330001)',
  'type': 'NTNC',
  'status': 'A',
  'county': 'ALLENDALE',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=201&tinwsys_st_code=SC&wsnumber=SC0330001   '},
 {'water_system_no': 'SC0870408',
  'water_system_name': 'ARROWHEAD MOTEL AND CG (0870408)',
  'type': 'NC',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=878&tinwsys_st_code=SC&wsnumber=SC0870408   '},
 {'water_system_no': 'SC2370678',
  'water_system_name': 'ASBURY HILL UMC CAMP (SC2370678)',
  'type': 'NC',
  'status': 'A',
  'county': 'GREENVILLE',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=2447&tinwsys_st_code=SC&wsnumber=SC2370678   '},
 {'water_system_no': 'SC0270402',
  'water_system_name': 'ASHLEY MOTOR MOTEL (SC0270402)',
  'type': 'NC',
  'status': 'A',
  'county': 'AIKEN',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=160&tinwsys_st_code=SC&wsnumber=SC0270402   '},
 {'water_system_no': 'SC0270915',
  'water_system_name': 'ATTA (SC0270915)',
  'type': 'NC',
  'status': 'A',
  'county': 'AIKEN',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=5383&tinwsys_st_code=SC&wsnumber=SC0270915   '},
 {'water_system_no': 'SC3970204',
  'water_system_name': "AUNT SUE'S COUNTRY STORE",
  'type': 'NC',
  'status': 'A',
  'county': 'PICKENS',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=4174&tinwsys_st_code=SC&wsnumber=SC3970204   '},
 {'water_system_no': 'SC1010504',
  'water_system_name': 'AWENDAW TOWN OF (SC1010504)',
  'type': 'C',
  'status': 'A',
  'county': 'CHARLESTON',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=6674&tinwsys_st_code=SC&wsnumber=SC1010504   '},
 {'water_system_no': 'SC2670925',
  'water_system_name': 'B&B MIDLAND MARKET (2670925)',
  'type': 'NC',
  'status': 'A',
  'county': 'HORRY',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=2841&tinwsys_st_code=SC&wsnumber=SC2670925   '},
 {'water_system_no': 'SC0572002',
  'water_system_name': 'B&D BBQ (SC0572002)',
  'type': 'NC',
  'status': 'A',
  'county': 'BAMBERG',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=5247&tinwsys_st_code=SC&wsnumber=SC0572002   '},
 {'water_system_no': 'SC2370908',
  'water_system_name': 'BALD ROCK HOA (SC2370908)',
  'type': 'NTNC',
  'status': 'A',
  'county': 'GREENVILLE',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=2477&tinwsys_st_code=SC&wsnumber=SC2370908   '},
 {'water_system_no': 'SC0510001',
  'water_system_name': 'BAMBERG PUBLIC WORKS (SC0510001)',
  'type': 'C',
  'status': 'A',
  'county': 'BAMBERG',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=383&tinwsys_st_code=SC&wsnumber=SC0510001   '},
 {'water_system_no': 'SC2170915',
  'water_system_name': 'BANDITS CASH & CARRY (SC2170915)',
  'type': 'NC',
  'status': 'A',
  'county': 'FLORENCE',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=2251&tinwsys_st_code=SC&wsnumber=SC2170915   '},
 {'water_system_no': 'SC4170802',
  'water_system_name': 'BARN CAMPGROUND (SC4170802)',
  'type': 'NC',
  'status': 'A',
  'county': 'SALUDA',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=4459&tinwsys_st_code=SC&wsnumber=SC4170802   '},
 {'water_system_no': 'SC0610001',
  'water_system_name': 'BARNWELL TOWN OF (SC0610001)',
  'type': 'C',
  'status': 'A',
  'county': 'BARNWELL',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=412&tinwsys_st_code=SC&wsnumber=SC0610001   '},
 {'water_system_no': 'SC0770233',
  'water_system_name': 'BARONY HOUSE/THE INN (SC0770233)',
  'type': 'NC',
  'status': 'A',
  'county': 'BEAUFORT',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=625&tinwsys_st_code=SC&wsnumber=SC0770233   '},
 {'water_system_no': 'SC1420002',
  'water_system_name': 'BARRINEAU WATER SYSTEM (SC1420002)',
  'type': 'C',
  'status': 'A',
  'county': 'CLARENDON',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=1489&tinwsys_st_code=SC&wsnumber=SC1420002   '},
 {'water_system_no': 'SC3260164',
  'water_system_name': 'BASIN ROCK MHP (SC3260164)',
  'type': 'C',
  'status': 'A',
  'county': 'LEXINGTON',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=3571&tinwsys_st_code=SC&wsnumber=SC3260164   '},
 {'water_system_no': 'SC3210002',
  'water_system_name': 'BATESBURG LEESVILLE DPW (SC3210002)',
  'type': 'C',
  'status': 'A',
  'county': 'LEXINGTON',
  'source_type': 'SWP',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=3328&tinwsys_st_code=SC&wsnumber=SC3210002   '},
 {'water_system_no': 'SC0220003',
  'water_system_name': 'BATH W&SD (SC0220003)',
  'type': 'C',
  'status': 'A',
  'county': 'AIKEN',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=65&tinwsys_st_code=SC&wsnumber=SC0220003   '},
 {'water_system_no': 'SC4050031',
  'water_system_name': 'BAY CAPITAL WATER WORKS (SC4050031)',
  'type': 'C',
  'status': 'A',
  'county': 'RICHLAND',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=4242&tinwsys_st_code=SC&wsnumber=SC4050031   '},
 {'water_system_no': 'SC3750027',
  'water_system_name': 'BAY RIDGE S/D (SC3750027)',
  'type': 'C',
  'status': 'A',
  'county': 'OCONEE',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=3923&tinwsys_st_code=SC&wsnumber=SC3750027   '},
 {'water_system_no': 'SC0820009',
  'water_system_name': 'BCWSA EAST COOPER (SC0820009)',
  'type': 'C',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'SWP',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=705&tinwsys_st_code=SC&wsnumber=SC0820009   '},
 {'water_system_no': 'SC0820004',
  'water_system_name': 'BCWSA LAKE MOULTRIE ESTATES (0820004)',
  'type': 'C',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'SWP',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=700&tinwsys_st_code=SC&wsnumber=SC0820004   '},
 {'water_system_no': 'SC0874018',
  'water_system_name': 'BCWSA MT HOLLY (SC0874018)',
  'type': 'NTNC',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'SWP',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=7218&tinwsys_st_code=SC&wsnumber=SC0874018   '},
 {'water_system_no': 'SC0820002',
  'water_system_name': 'BCWSA SANGAREE W/D (0820002)',
  'type': 'C',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'SWP',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=698&tinwsys_st_code=SC&wsnumber=SC0820002   '},
 {'water_system_no': 'SC0850018',
  'water_system_name': 'BCWSA SINEATH MHP (0850018)',
  'type': 'C',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'SWP',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=750&tinwsys_st_code=SC&wsnumber=SC0850018   '},
 {'water_system_no': 'SC4672022',
  'water_system_name': "BEAR'S DEN THE (SC4672022)",
  'type': 'NC',
  'status': 'A',
  'county': 'YORK',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=7138&tinwsys_st_code=SC&wsnumber=SC4672022   '},
 {'water_system_no': 'SC0772001',
  'water_system_name': 'BEAUFORT CO BOAT LNDNG-DAUFUSKIE(0772001',
  'type': 'NC',
  'status': 'A',
  'county': 'BEAUFORT',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=668&tinwsys_st_code=SC&wsnumber=SC0772001   '},
 {'water_system_no': 'SC0760016',
  'water_system_name': 'BEAUFORT MHP (0760016)',
  'type': 'C',
  'status': 'A',
  'county': 'BEAUFORT',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=536&tinwsys_st_code=SC&wsnumber=SC0760016   '},
 {'water_system_no': 'SC0220004',
  'water_system_name': 'BEECH ISLAND W/D (SC0220004)',
  'type': 'C',
  'status': 'A',
  'county': 'AIKEN',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=66&tinwsys_st_code=SC&wsnumber=SC0220004   '},
 {'water_system_no': 'SC2370802',
  'water_system_name': 'BEECH SPRINGS CAMPGROUND (SC2370802)',
  'type': 'NC',
  'status': 'A',
  'county': 'GREENVILLE',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=2459&tinwsys_st_code=SC&wsnumber=SC2370802   '},
 {'water_system_no': 'SC4060009',
  'water_system_name': 'BEL AIR MHP (SC4060009)',
  'type': 'C',
  'status': 'A',
  'county': 'RICHLAND',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=4251&tinwsys_st_code=SC&wsnumber=SC4060009   '},
 {'water_system_no': 'SC3870418',
  'water_system_name': 'BELLS MARINA 1 (SC3870418)',
  'type': 'NC',
  'status': 'A',
  'county': 'ORANGEBURG',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=4091&tinwsys_st_code=SC&wsnumber=SC3870418   '},
 {'water_system_no': 'SC0410004',
  'water_system_name': 'BELTON CITY OF (SC0410004)',
  'type': 'C',
  'status': 'A',
  'county': 'ANDERSON',
  'source_type': 'SWP',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=217&tinwsys_st_code=SC&wsnumber=SC0410004   '},
 {'water_system_no': 'SC0470909',
  'water_system_name': 'BELTON GUN CLUB INC (0470909)',
  'type': 'NC',
  'status': 'A',
  'county': 'ANDERSON',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=379&tinwsys_st_code=SC&wsnumber=SC0470909   '},
 {'water_system_no': 'SC0410011',
  'water_system_name': 'BELTON-HONEA PATH WA (SC0410011)',
  'type': 'C',
  'status': 'A',
  'county': 'ANDERSON',
  'source_type': 'SW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=222&tinwsys_st_code=SC&wsnumber=SC0410011   '},
 {'water_system_no': 'SC3410001',
  'water_system_name': 'BENNETTSVILLE CITY OF (SC3410001)',
  'type': 'C',
  'status': 'A',
  'county': 'MARLBORO',
  'source_type': 'SW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=3737&tinwsys_st_code=SC&wsnumber=SC3410001   '},
 {'water_system_no': 'SC1030028',
  'water_system_name': 'BERKELEY ELECTRIC COOP (1030028)',
  'type': 'NTNC',
  'status': 'A',
  'county': 'CHARLESTON',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=6817&tinwsys_st_code=SC&wsnumber=SC1030028   '},
 {'water_system_no': 'SC0870202',
  'water_system_name': 'BERKELEY YACHT CLUB (SC0870202)',
  'type': 'NC',
  'status': 'A',
  'county': 'BERKELEY',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=807&tinwsys_st_code=SC&wsnumber=SC0870202   '},
 {'water_system_no': 'SC4670900',
  'water_system_name': 'BETHELWOODS CENTER (SC4670900)',
  'type': 'NC',
  'status': 'A',
  'county': 'YORK',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=5180&tinwsys_st_code=SC&wsnumber=SC4670900   '},
 {'water_system_no': 'SC4670120',
  'water_system_name': 'BETHESDA PRSBYTRN CHILD DVLPMNT(4670120)',
  'type': 'NTNC',
  'status': 'A',
  'county': 'YORK',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=5103&tinwsys_st_code=SC&wsnumber=SC4670120   '},
 {'water_system_no': 'SC3920003',
  'water_system_name': 'BETHLEHEM-ROANOKE W/D (SC3920003)',
  'type': 'C',
  'status': 'A',
  'county': 'PICKENS',
  'source_type': 'SWP',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=4146&tinwsys_st_code=SC&wsnumber=SC3920003   '},
 {'water_system_no': 'SC2820006',
  'water_system_name': 'BETHUNE RURAL WATER (SC2820006)',
  'type': 'C',
  'status': 'A',
  'county': 'KERSHAW',
  'source_type': 'GW',
  'link': 'WaterSystemDetail.jsp?tinwsys_is_number=3103&tinwsys_st_code=SC&wsnumber=SC2820006   '},
 {'water_system_no': 'SC2810002',
  'water_system_name': 'BETHUNE TOWN OF (SC2810002)',
  'type': 'C',
  'status': 'A',
  'county': 'KERSHAW',

In [59]:
df = pd.DataFrame(rows)
df.head()

,water_system_no,water_system_name,type,status,county,source_type,link
0,SC7777,123 WATER,,A,,,None
1,SC0874019,"1250 OLD GILLIARD, LLC (SC0874019",NC,A,BERKELEY,GW,None
2,SC2174000,341 EXPRESS (SC2174000),NC,A,FLORENCE,GW,None
3,SC4570950,4 WAY STOP (SC4570950),NC,A,WILLIAMSBURG,GW,None
4,SC4060012,611 HARMON LLC (SC4060012),C,A,RICHLAND,GW,None

In [60]:
df.to_csv('water.csv', index=False)